{{- if and .Values.backend.persistence.enabled (not .Values.backend.persistence.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "turbo-ea.fullname" . }}-backend-data
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "turbo-ea.componentLabels" (dict "root" . "component" "backend") | nindent 4 }}
  {{- with (merge (dict) .Values.backend.persistence.annotations .Values.commonAnnotations) }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    {{- toYaml .Values.backend.persistence.accessModes | nindent 4 }}
  {{- with .Values.backend.persistence.storageClass }}
  storageClassName: {{ . | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.backend.persistence.size }}
{{- end }}
