{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "turbo-ea.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "turbo-ea.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  {{ .Values.existingSecretKeys.secretKey }}: {{ .Values.secretKey | quote }}
  {{ .Values.existingSecretKeys.postgresPassword }}: {{ .Values.postgresql.password | quote }}
{{- end }}
