"""The bundled brand-icon pack offered as a card logo.

An agent setting logos across a whole application portfolio would otherwise
have to hand-carry two to seven thousand characters of base64 per card — the
dominant cost of the job, and the dominant risk, since every one of those
payloads is an independent chance to corrupt something. Resolving an icon by
slug instead turns that into one small call.

Resolution lives here, in the backend, rather than in the MCP server: this is
where logo bytes are stored, the pack ships in this image, and a web client
could offer the same icons later without a second copy of the pack.

The icons are pre-rasterised PNGs, generated by
``frontend/scripts/gen-brand-icons.mjs`` and committed. They are not rendered
at runtime and this module has no image dependency — the product deliberately
refuses SVG (see ``app/api/v1/card_logos.py``), so shipping vectors would have
meant adding a renderer to serve them. Each icon carries its own official brand
colour, baked in at generation time; there is no tint parameter for the same
reason.

Security: ``icon_slug`` is caller-controlled and becomes a filename. Resolution
therefore checks membership in the parsed index *first* and only then touches
the filesystem, so no path is ever built from unvalidated input. The character
allowlist in ``_SLUG_RE`` is belt-and-braces on top of that.
"""

from __future__ import annotations

import json
import re
from functools import lru_cache
from pathlib import Path

_ICON_DIR: Path = Path(__file__).parent / "data" / "brand_icons"
_INDEX_PATH: Path = _ICON_DIR / "index.json"

# Accepted-and-stripped rather than required, so `simpleicons:sap` and `sap`
# both work and a second pack can be added later without a wire break.
_PACK_PREFIX = "simpleicons:"
_SLUG_RE = re.compile(r"^[a-z0-9._-]{1,64}$")

BRAND_ICON_MIME = "image/png"


def normalise_slug(raw: str | None) -> str | None:
    """Return the canonical slug for a caller-supplied value, or None."""
    if not raw:
        return None
    slug = raw.strip().lower()
    if slug.startswith(_PACK_PREFIX):
        slug = slug[len(_PACK_PREFIX) :]
    return slug if _SLUG_RE.match(slug) else None


@lru_cache(maxsize=1)
def _index_by_slug() -> dict[str, dict[str, str]]:
    """Slug → {slug, title, hex}, parsed once."""
    if not _INDEX_PATH.exists():
        return {}
    with _INDEX_PATH.open("r", encoding="utf-8") as f:
        entries = json.load(f)
    return {e["slug"]: e for e in entries if e.get("slug")}


def icon_count() -> int:
    """How many icons the bundled pack carries."""
    return len(_index_by_slug())


# Bounded so a full batch of uploads does not re-read the same files from disk,
# without pinning the whole pack (3400 × ~2 KB) in memory for the life of the
# process.
@lru_cache(maxsize=256)
def _read_icon_bytes(slug: str) -> bytes:
    return (_ICON_DIR / f"{slug}.png").read_bytes()


def resolve_brand_icon(raw: str | None) -> tuple[bytes, str, dict[str, str]] | None:
    """Resolve a slug to ``(png_bytes, mime, index_entry)``, or None.

    Returns None for an unknown or malformed slug — never raises, so a caller
    can report it as a bad request rather than a server error.
    """
    slug = normalise_slug(raw)
    if slug is None:
        return None
    entry = _index_by_slug().get(slug)
    if entry is None:
        return None
    try:
        return _read_icon_bytes(slug), BRAND_ICON_MIME, entry
    except OSError:
        # The index and the files disagree — a half-run generator. Treat it as
        # unknown rather than 500ing on a request the caller cannot fix.
        return None


def search_brand_icons(search: str, limit: int) -> list[dict[str, str]]:
    """Search the pack by slug and title.

    Ranked exact → starts-with → contains, alphabetical within a tier, the
    same shape as card search — so a caller typing "sap" gets SAP first rather
    than the dozen brands that merely contain those letters.
    """
    entries = list(_index_by_slug().values())
    term = (search or "").strip().lower()
    if not term:
        return sorted(entries, key=lambda e: e["slug"])[:limit]

    def rank(entry: dict[str, str]) -> tuple[int, str]:
        slug = entry["slug"]
        title = entry.get("title", "").lower()
        if slug == term or title == term:
            return (0, slug)
        if slug.startswith(term) or title.startswith(term):
            return (1, slug)
        return (2, slug)

    matched = [e for e in entries if term in e["slug"] or term in e.get("title", "").lower()]
    return sorted(matched, key=rank)[:limit]
