"""The bundled brand-icon pack offered as a card logo.

An agent setting logos across a whole application portfolio would otherwise
have to hand-carry two to seven thousand characters of base64 per card — the
dominant cost of the job, and the dominant risk, since every one of those
payloads is an independent chance to corrupt something. Resolving an icon by
slug instead turns that into one small call.

Resolution lives here, in the backend, rather than in the MCP server: this is
where logo bytes are stored, the pack ships in this image, and a web client
could offer the same icons later without a second copy of the pack.

The icons are pre-rasterised PNGs, generated by
``frontend/scripts/gen-brand-icons.mjs`` and committed. They are not rendered
at runtime and this module has no image dependency — the product deliberately
refuses SVG (see ``app/api/v1/card_logos.py``), so shipping vectors would have
meant adding a renderer to serve them. Colour is baked in at generation time;
there is no tint parameter for the same reason.

**Two packs**, both CC0:

``logos``
    SVG Logos (gilbarbara) — the real, full-colour marks, 2110 of them. Many
    are wordmarks and are therefore NOT square; every surface that draws a
    logo uses ``object-fit: contain``, so a wide mark letterboxes.
``simpleicons``
    Simple Icons — one flat brand colour per mark, 3453 of them. Broader
    coverage, and the fallback wherever the colour set has nothing.

A caller may address either exactly (``logos:sap``, ``simpleicons:sap``). A
**bare** slug resolves to the colour pack first, because a reader recognises
Google's four colours far faster than a grey silhouette of them; 605 slugs
exist in both.

**Storage.** Two files, not 3453: ``brand_icons.pack`` is every PNG
concatenated, and ``brand_icons.json`` records ``offset``/``length`` per slug.
A file per icon made the review diff unusable and silently truncated CI's
changed-file detection, which caps at 3000 entries. Reads are ``os.pread`` on
one descriptor: O(1), no seek state, and safe to call from several threads
because ``pread`` does not move the file offset.

**Security.** ``icon_slug`` is caller-controlled and never becomes a path — it
is a key into the parsed index, and the only file this module ever opens is
the pack itself, whose name is a constant. There is no string for a traversal
to hide in. ``_SLUG_RE`` and the index-membership check are belt-and-braces on
top of that, not the thing keeping it safe.
"""

from __future__ import annotations

import json
import os
import re
import threading
from functools import lru_cache
from pathlib import Path

_DATA_DIR: Path = Path(__file__).parent / "data"
_PACK_PATH: Path = _DATA_DIR / "brand_icons.pack"
_INDEX_PATH: Path = _DATA_DIR / "brand_icons.json"

# Pack names, in the order a bare slug is resolved. Colour first — see the
# module docstring.
_PACKS = ("logos", "simpleicons")
_SLUG_RE = re.compile(r"^[a-z0-9._-]{1,64}$")

BRAND_ICON_MIME = "image/png"

# Guards only the lazy open, not the reads — `pread` needs no serialisation.
_fd_lock = threading.Lock()
_fd: int | None = None


def parse_ref(raw: str | None) -> tuple[str | None, str] | None:
    """Split a caller-supplied reference into ``(pack, slug)``, or None.

    ``"logos:sap"`` pins the pack; a bare ``"sap"`` leaves it None, meaning
    "whichever pack has it, colour first". An unknown pack name is rejected
    rather than silently treated as part of the slug, so a typo surfaces as an
    unknown icon instead of quietly resolving to something else.
    """
    if not raw:
        return None
    value = raw.strip().lower()
    pack: str | None = None
    if ":" in value:
        prefix, _, rest = value.partition(":")
        if prefix not in _PACKS:
            return None
        pack, value = prefix, rest
    return (pack, value) if _SLUG_RE.match(value) else None


def normalise_slug(raw: str | None) -> str | None:
    """The bare slug for a caller-supplied value, or None. Drops the pack."""
    parsed = parse_ref(raw)
    return parsed[1] if parsed else None


@lru_cache(maxsize=1)
def _entries() -> list[dict]:
    """Every index entry, in pack order, parsed once."""
    if not _INDEX_PATH.exists():
        return []
    with _INDEX_PATH.open("r", encoding="utf-8") as f:
        return [e for e in json.load(f) if e.get("slug") and e.get("pack")]


@lru_cache(maxsize=1)
def _by_ref() -> dict[tuple[str, str], dict]:
    """(pack, slug) → entry. The exact address."""
    return {(e["pack"], e["slug"]): e for e in _entries()}


@lru_cache(maxsize=1)
def _by_slug() -> dict[str, dict]:
    """Slug → the entry a BARE slug resolves to, colour pack first.

    Built by walking `_PACKS` in order and refusing to overwrite, so the
    preference is expressed once, here, rather than depending on the order the
    generator happened to emit.
    """
    out: dict[str, dict] = {}
    for pack in _PACKS:
        for e in _entries():
            if e["pack"] == pack:
                out.setdefault(e["slug"], e)
    return out


def _lookup(pack: str | None, slug: str) -> dict | None:
    return _by_ref().get((pack, slug)) if pack else _by_slug().get(slug)


def icon_count() -> int:
    """How many icons the bundled packs carry, across both."""
    return len(_entries())


def _pack_fd() -> int | None:
    """The pack's file descriptor, opened once and kept for the process.

    Deliberately a descriptor rather than a re-opened file per read: the pack
    is opened at most once, and `pread` against it is a single syscall with no
    shared cursor to race on.
    """
    global _fd
    if _fd is not None:
        return _fd
    with _fd_lock:
        if _fd is None:  # re-check: another thread may have won the race
            try:
                _fd = os.open(_PACK_PATH, os.O_RDONLY)
            except OSError:
                return None
    return _fd


def _read_icon_bytes(slug: str, pack: str | None = None) -> bytes | None:
    """The icon's bytes, or None when the packs have no such entry.

    Not cached: a read is one `pread` of ~2 KB out of the page cache, which is
    cheaper than the dict of `bytes` a cache would pin.
    """
    entry = _lookup(pack, slug)
    if entry is None:
        return None
    fd = _pack_fd()
    if fd is None:
        return None
    length = entry.get("length") or 0
    offset = entry.get("offset")
    if not length or offset is None:
        return None
    data = os.pread(fd, length, offset)
    # A short read means the index and the pack disagree — a half-written
    # generator run. Report it as unknown rather than serving a truncated PNG.
    return data if len(data) == length else None


def resolve_brand_icon(raw: str | None) -> tuple[bytes, str, dict] | None:
    """Resolve a reference to ``(png_bytes, mime, index_entry)``, or None.

    Accepts ``"sap"``, ``"logos:sap"`` or ``"simpleicons:sap"``. Returns None
    for anything unknown or malformed — never raises, so a caller can report
    it as a bad request rather than a server error.
    """
    parsed = parse_ref(raw)
    if parsed is None:
        return None
    pack, slug = parsed
    entry = _lookup(pack, slug)
    if entry is None:
        return None
    try:
        data = _read_icon_bytes(slug, pack)
    except OSError:
        # The pack is present but unreadable — a truncated volume, a bad mode.
        return None
    if data is None:
        return None
    return data, BRAND_ICON_MIME, entry


def search_brand_icons(search: str, limit: int) -> list[dict[str, str]]:
    """Search the packs by slug and title.

    Ranked exact → starts-with → contains, alphabetical within a tier, the
    same shape as card search — so a caller typing "sap" gets SAP first rather
    than the dozen brands that merely contain those letters.

    Deduplicated by slug: a slug in both packs appears once, as whichever the
    bare form resolves to. Showing "SAP" twice — once in colour, once as a
    silhouette — would make the picker look broken and give an agent two
    indistinguishable choices.
    """
    entries = list(_by_slug().values())
    term = (search or "").strip().lower()

    def public(entry: dict) -> dict[str, str]:
        # `ref` is the address to hand back: it pins the pack, so a caller that
        # picked the colour SAP cannot be served the silhouette later if the
        # preference order ever changes. Offsets stay private — they are an
        # implementation detail of the storage format.
        return {
            "ref": f"{entry['pack']}:{entry['slug']}",
            "slug": entry["slug"],
            "title": entry.get("title", ""),
            "pack": entry["pack"],
            **({"hex": entry["hex"]} if entry.get("hex") else {}),
        }

    if not term:
        return [public(e) for e in sorted(entries, key=lambda e: e["slug"])[:limit]]

    def rank(entry: dict) -> tuple[int, str]:
        slug = entry["slug"]
        title = entry.get("title", "").lower()
        if slug == term or title == term:
            return (0, slug)
        if slug.startswith(term) or title.startswith(term):
            return (1, slug)
        return (2, slug)

    matched = [e for e in entries if term in e["slug"] or term in e.get("title", "").lower()]
    return [public(e) for e in sorted(matched, key=rank)[:limit]]
