"""NexaTech Industries demo — card logos.

Puts a product's own mark on the demo Applications and IT Components, so a
fresh ``SEED_DEMO=true`` boot shows the card-logo feature rather than a wall of
identical type icons: the card header, the Inventory **Logo** column, published
web portals, DrawIO diagrams and the Layered Dependency View all render one.

Two sources, no network:

``BRAND_LOGOS``
    Real products, resolved by slug out of the bundled brand-icon packs
    (``app/services/brand_icons.py``). The pack ships inside the image, so this
    works on an air-gapped install exactly as it does anywhere else.
``HOUSE_LOGOS``
    NexaTech's own software, which by construction has no mark in the world.
    Generated by ``frontend/scripts/gen-demo-logos.mjs`` into ``data/demo_logos``
    and committed.

**Not every card gets one, deliberately.** Roughly a third keep their card-type
icon, in two groups that are both honest outcomes rather than gaps to paper
over: brands the CC0 packs do not carry (ServiceNow, Workday, DocuSign, Coupa,
Altium, MATLAB…), and generic internal services and shadow IT — giving *Sales
Contact Workbook* a polished logo would misrepresent what it is. A landscape
where some cards have marks and some do not is what a real one looks like, and
it exercises the fallback the feature actually ships.

Idempotent via the durable marker in ``app_settings.general_settings.demoSeeded``
(see ``seed_markers``), so deleting a logo never brings it back on the next
restart. A separate seeder key rather than an addition to ``seed_demo_extras``
precisely because extras is already marked complete on every existing demo
install and would never run again.
"""

from __future__ import annotations

import uuid
from pathlib import Path

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.models.card import Card
from app.models.card_logo import CardLogo
from app.models.card_type import CardType
from app.models.user import User
from app.services.brand_icons import BRAND_ICON_MIME, resolve_brand_icon
from app.services.seed_markers import demo_seed_completed, mark_demo_seed_completed

HOUSE_LOGO_DIR: Path = Path(__file__).parent / "data" / "demo_logos"
HOUSE_LOGO_MIME = "image/png"

# ===================================================================
# BRAND MARKS — (card name, brand-icon ref)
#
# Refs are deliberately PACK-PINNED (``logos:sap``, never a bare ``sap``). A
# bare slug resolves colour-pack-first today, but that is documented as a
# preference rather than a contract, so pinning is what stops the demo's
# appearance shifting if the preference order is ever revisited. It is also the
# exact ``ref`` shape ``search_brand_icons`` hands back to the picker.
# ===================================================================
BRAND_LOGOS: tuple[tuple[str, str], ...] = (
    # ── Applications ────────────────────────────────────────────────
    ("SAP S/4HANA", "logos:sap"),
    ("SAP Ariba", "logos:sap"),
    ("SAP SuccessFactors", "logos:sap"),
    ("Siemens Teamcenter", "simpleicons:siemens"),
    ("Siemens NX", "simpleicons:siemens"),
    ("Siemens Opcenter", "simpleicons:siemens"),
    ("Siemens Opcenter APS", "simpleicons:siemens"),
    ("Bitbucket", "logos:bitbucket"),
    ("Jenkins", "logos:jenkins"),
    ("Jira", "logos:jira"),
    ("Confluence", "logos:confluence"),
    ("Azure IoT Hub", "logos:microsoft-azure"),
    ("Grafana", "logos:grafana"),
    ("Apache Kafka", "simpleicons:apachekafka"),
    ("TimescaleDB Manager", "simpleicons:timescale"),
    ("Power BI", "logos:microsoft-power-bi"),
    ("Salesforce Sales Cloud", "logos:salesforce"),
    ("Salesforce Service Cloud", "logos:salesforce"),
    ("Salesforce CPQ", "logos:salesforce"),
    ("HubSpot Marketing", "logos:hubspot"),
    ("Microsoft 365", "logos:microsoft"),
    ("Microsoft Teams", "logos:microsoft-teams"),
    ("Microsoft Entra ID", "logos:microsoft"),
    ("Okta", "logos:okta"),
    ("Tableau", "logos:tableau"),
    ("Snowflake", "logos:snowflake"),
    ("GitHub Actions", "simpleicons:githubactions"),
    ("SonarQube", "logos:sonarqube"),
    ("HashiCorp Vault", "logos:vault"),
    ("Splunk", "logos:splunk"),
    # ── IT Components ───────────────────────────────────────────────
    ("PostgreSQL 16", "logos:postgresql"),
    ("Redis 7", "logos:redis"),
    ("Nginx", "logos:nginx"),
    ("Node.js 20 LTS", "logos:nodejs"),
    ("Python 3.12", "logos:python"),
    (".NET 8", "logos:dotnet"),
    ("React 18", "logos:react"),
    ("Datadog", "logos:datadog"),
    ("PagerDuty", "logos:pagerduty"),
    ("GitHub Enterprise", "logos:github"),
    ("Dell PowerEdge R760", "simpleicons:dell"),
    ("HPE ProLiant DL380", "simpleicons:hp"),
    ("Cisco Catalyst 9300", "simpleicons:cisco"),
    ("Fortinet FortiGate 600F", "simpleicons:fortinet"),
    ("NetApp AFF A400", "simpleicons:netapp"),
    ("Azure Kubernetes Service", "logos:microsoft-azure"),
    ("Azure SQL Database", "logos:microsoft-azure"),
    ("Azure Event Hubs", "logos:microsoft-azure"),
    ("Azure DevOps", "logos:microsoft-azure"),
    ("Azure Virtual Machines", "logos:microsoft-azure"),
    ("Azure Monitor", "logos:microsoft-azure"),
    ("AWS EC2", "logos:aws"),
    ("SalesTrack Oracle Database", "logos:oracle"),
)

# ===================================================================
# HOUSE MARKS — (card name, PNG file stem under data/demo_logos)
#
# NexaTech's own product family. Regenerate with `npm run gen:demo-logos`.
# ===================================================================
HOUSE_LOGOS: tuple[tuple[str, str], ...] = (
    ("NexaSCADA", "nexascada"),
    ("NexaCloud IoT Platform", "nexacloud"),
    ("NexaPortal", "nexaportal"),
    ("NexaMobile App", "nexamobile"),
    ("NexaConnect Device Manager", "nexaconnect"),
    ("NexaTech Commerce Portal", "nexacommerce"),
)


def house_logo_path(stem: str) -> Path:
    """On-disk path of a house mark. Exposed so tests can assert it exists."""
    return HOUSE_LOGO_DIR / f"{stem}.png"


# ===================================================================
# Public entry point
# ===================================================================
SEEDER_KEY = "logos"


async def seed_logo_demo_data(db: AsyncSession) -> dict:
    """Attach demo card logos to existing NexaTech Applications / IT Components.

    Cards are matched by exact name and silently skipped when absent, so the
    seeder stays compatible with a partial-demo install — the same contract
    ``seed_demo_security`` keeps.

    Note what this deliberately does **not** do: it writes no card event and
    never touches ``cards.updated_at``. That falls out of ``card_logos`` being
    a side table (see ``app/models/card_logo.py``), which is exactly why the
    Inventory **Modified** column keeps meaning "content last changed" — a
    seeded logo must not re-date three hundred cards.
    """
    if await demo_seed_completed(db, SEEDER_KEY):
        return {"skipped": True, "reason": "already seeded"}

    # Legacy guard for installs that seeded before this seeder existed: logos
    # are only created here, so any row means we already ran. Record the marker
    # now so the install stops relying on the inference.
    existing = await db.execute(select(CardLogo.id).limit(1))
    if existing.scalar_one_or_none() is not None:
        await mark_demo_seed_completed(db, SEEDER_KEY)
        await db.commit()
        return {"skipped": True, "reason": "card logos already exist"}

    admin_result = await db.execute(select(User.id).where(User.role == "admin").limit(1))
    admin_id = admin_result.scalar_one_or_none()
    if admin_id is None:
        return {"skipped": True, "reason": "no admin user found"}

    # Only types that actually offer logos. Checking here means the seeder can
    # never create a row `POST /cards/{id}/logo` would itself have refused.
    allowed_types = set(
        (await db.execute(select(CardType.key).where(CardType.allow_card_logo.is_(True))))
        .scalars()
        .all()
    )
    if not allowed_types:
        return {"skipped": True, "reason": "no card type allows logos"}

    card_rows = await db.execute(select(Card.id, Card.name, Card.type))
    name_to_id: dict[str, uuid.UUID] = {
        row.name: row.id for row in card_rows.all() if row.type in allowed_types
    }

    brand_count = 0
    house_count = 0

    for card_name, ref in BRAND_LOGOS:
        card_id = name_to_id.get(card_name)
        if not card_id:
            continue
        resolved = resolve_brand_icon(ref)
        if resolved is None:
            # A ref the packs no longer carry. The unit tests pin every ref, so
            # this is a torn pack rather than a bad mapping — skip the card
            # rather than abort the whole demo seed over one icon.
            continue
        data, _mime, _entry = resolved
        db.add(
            CardLogo(
                id=uuid.uuid4(),
                card_id=card_id,
                mime_type=BRAND_ICON_MIME,
                size=len(data),
                data=data,
                created_by=admin_id,
            )
        )
        brand_count += 1

    for card_name, stem in HOUSE_LOGOS:
        card_id = name_to_id.get(card_name)
        if not card_id:
            continue
        path = house_logo_path(stem)
        try:
            data = path.read_bytes()
        except OSError:
            continue
        db.add(
            CardLogo(
                id=uuid.uuid4(),
                card_id=card_id,
                mime_type=HOUSE_LOGO_MIME,
                size=len(data),
                data=data,
                created_by=admin_id,
            )
        )
        house_count += 1

    await db.flush()
    await mark_demo_seed_completed(db, SEEDER_KEY)
    await db.commit()
    return {
        "brand_logos": brand_count,
        "house_logos": house_count,
    }
